package li.pitschmann.knx.logic.db.strategies;

import li.pitschmann.knx.core.utils.Stopwatch;
import li.pitschmann.knx.logic.components.OutboxComponentImpl;
import li.pitschmann.knx.logic.db.DatabaseManager;
import li.pitschmann.knx.logic.db.dao.ComponentsDao;
import li.pitschmann.knx.logic.db.jdbi.mappers.ComponentType;
import li.pitschmann.knx.logic.db.models.ComponentModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.TimeUnit;

/**
 * {@link PersistenceStrategy} implementation for {@link OutboxComponentImpl}
 *
 * @author PITSCHR
 */
public class OutboxComponentPersistenceStrategy extends AbstractComponentPersistenceStrategy<OutboxComponentImpl> {
    private static final Logger LOG = LoggerFactory.getLogger(OutboxComponentPersistenceStrategy.class);

    public OutboxComponentPersistenceStrategy(final DatabaseManager databaseManager) {
        super(databaseManager);
    }

    @Override
    protected int insert(final OutboxComponentImpl component) {
        final var sw = Stopwatch.createStarted();
        LOG.trace("Database write request for outbox component: {}", component);

        final var componentModel = ComponentModel.builder()
                .uid(component.getUid())
                .className(component.getWrappedObject().getClass().getName())
                .componentType(ComponentType.OUTBOX)
                .build();

        // insert component
        final var componentId = verifyAutoGeneratedKey(databaseManager.dao(ComponentsDao.class).insert(componentModel));

        insertConnectors(componentId, component.getInputConnectors());

        // insert event key
        insertEventKey(componentId, component.getEventKey());

        LOG.info("Outbox component for class '{}' written to database (new id={}) and it took {} ms: {}", component.getClass().getName(),
                sw.elapsed(TimeUnit.MILLISECONDS), componentId, component);

        return componentId;
    }

    @Override
    protected int update(final ComponentModel componentModel, final OutboxComponentImpl component) {
        // update connectors and related pins
        updateConnectors(componentModel, component.getInputConnectors());

        // update the event key model
        updateEventKey(componentModel, component.getEventKey());

        return componentModel.getId();
    }

    @Override
    public Class<OutboxComponentImpl> compatibleClass() {
        return OutboxComponentImpl.class;
    }
}
