package li.pitschmann.knx.logic.db.strategies;

import li.pitschmann.knx.core.utils.Preconditions;

/**
 * Strategy for database persistence
 *
 * @param <T> type of object to be stored
 * @author PITSCHR
 */
public interface PersistenceStrategy<T> {
    /**
     * Saves the object to database
     *
     * @param object object to be stored
     * @return {@code R} which allows the result
     */
    int save(T object);

    /**
     * Returns the compatible class for {@link PersistenceStrategy}
     *
     * @return {@link Class}
     */
    Class<T> compatibleClass();

    /**
     * Verifies if the auto-generated key is valid one. It must be positive.
     *
     * @param key the auto-generated key to be verified
     * @return the verified auto-generated key
     */
    default int verifyAutoGeneratedKey(final int key) {
        // new component id OK?
        Preconditions.checkArgument(key > 0,
                "Could not obtain a correct auto-generated key from database. Key returned: " + key
        );
        return key;
    }
}
